---

#
# デフォルトはjson-fileドライバーで無制限にログが溜まる
# パンクするので、30MBを超えたらローテートして5世代まで保存
#
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "30m"
    max-file: "5"

services:
  # clickhouse は公式
  # https://hub.docker.com/_/clickhouse
  clickhouse:
    logging:
      <<: *default-logging
    image: clickhouse:25.12.1
    # --ulimit "nofile=ソフトリミット:ハードリミット"
    # ファイルディスクリプタ数(同時に開けるファイル数)
    # デフォルトでは1024や4096あたりが多いが、DB用途では65536やそれ以上が推奨されることも多い
    # DBや高負荷なサーバープロセスは大量のファイルやネットワークソケットを同時に開く
    # デフォルト値のままだと上限に到達し、エラー（"Too many open files"など）を起こすことがある
    # そのため上限を上げておく
    # 262144 = 2^18
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    # 8123番はHTTP client interface
    # 9000番はNative client interface
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
    volumes:
      - type: bind
        source: ${PWD}/etc/clickhouse-server/docker-entrypoint-initdb.d/
        target: /docker-entrypoint-initdb.d/
      - type: volume
        source: clickhouse-data
        target: /var/lib/clickhouse/

  # grafana は公式
  # https://hub.docker.com/r/grafana/grafana
  grafana:
    logging:
      <<: *default-logging
    image: grafana/grafana:12.4.0-20585723282-ubuntu
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
      GF_USERS_DEFAULT_THEME: light
      GF_USERS_DEFAULT_LANGUAGE: ja-JP
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
      CLICKHOUSE_DEFAULT_DB: default
      CLICKHOUSE_DEFAULT_TABLE: results
    volumes:
      - type: volume
        source: grafana-plugins
        target: /var/lib/grafana/plugins/
      - type: bind
        source: ${PWD}/etc/grafana/provisioning/datasources/
        target: /etc/grafana/provisioning/datasources/
      - type: bind
        source: ${PWD}/etc/grafana/provisioning/dashboards/
        target: /etc/grafana/provisioning/dashboards/
      - type: bind
        source: ${PWD}/var/lib/grafana/dashboards/
        target: /var/lib/grafana/dashboards/

volumes:
  clickhouse-data:
  grafana-plugins: