{
 "title": "sample-dashboad",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "スコア", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "スコアの推移",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    toDateTime(started_at) AS started_at,\n    score AS \"スコア\"\nFROM results\nORDER BY started_at\n"
    }
   ]
  },
  {
   "title": "時間範囲内のベンチスコア",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select\nscore as \"スコア\"\n, dateDiff('second', started_at, ended_at) as \"時間(秒)\"\n, started_at as \"ベンチ開始\"\n, ended_at as \"ベンチ終了\"\nfrom results\nwhere started_at between $__fromTime and $__toTime\norder by started_at desc\nlimit 10\n;"
    }
   ]
  },
  { "title": "nx(パス・メソッド別のアクセスログ集計)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "時間範囲内の最新ベンチの Nginx のアクセスログ集計",
   "type": "table",
   "gridPos": { "h": 19, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "with latest_slow_run as (\nselect slow_run_started_at\nfrom nginx_access_runs\nwhere slow_run_started_at between $__fromTime and $__toTime\norder by slow_run_started_at desc\nlimit 1\n)\nselect\nuri\n, method\n, count as \"合計\"\n, c_2xx as \"2xx\"\n, c_3xx as \"3xx\"\n, c_4xx as \"4xx\"\n, c_5xx as \"5xx\"\n, sum as \"合計時間\"\n, min as \"最短時間\"\n, max as \"最長時間\"\n, avg as \"平均時間\"\n, p90 as \"p90時間\"\nfrom nginx_access_runs\nwhere slow_run_started_at = (select slow_run_started_at from latest_slow_run)\norder by sum desc\n;"
    }
   ]
  },
  {
   "title": "新規パネル",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with latest_slow_run as (\nselect slow_run_started_at\nfrom nginx_access_runs\nwhere slow_run_started_at between $__fromTime and $__toTime\norder by slow_run_started_at desc\nlimit 1\n)\nselect\n'Nginx',\nformatDateTime(toTimeZone(slow_run_started_at, 'Asia/Tokyo'),'%H:%i:%S') as \"最新ベンチ開始\"\nfrom latest_slow_run\nwhere slow_run_started_at between $__fromTime and $__toTime\norder by slow_run_started_at desc\nlimit 1\n;"
    }
   ]
  }
 ]
}