{
 "title": "sample-dashboad",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "スコア", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "スコアの推移",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    toDateTime(started_at) AS started_at,\n    score AS \"スコア\"\nFROM results\nORDER BY started_at\n"
    }
   ]
  },
  {
   "title": "時間範囲内のベンチスコア",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select\nscore as \"スコア\"\n, dateDiff('second', started_at, ended_at) as \"時間(秒)\"\n, started_at as \"ベンチ開始\"\n, ended_at as \"ベンチ終了\"\nfrom results\nwhere started_at between $__fromTime and $__toTime\norder by started_at desc\nlimit 10\n;"
    }
   ]
  },
  { "title": "nx(パス・メソッド別のアクセスログ集計)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "時間範囲内の最新ベンチの Nginx のアクセスログ集計",
   "type": "table",
   "gridPos": { "h": 19, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "with latest_slow_run as (\nselect slow_run_started_at\nfrom nginx_access_runs\nwhere slow_run_started_at between $__fromTime and $__toTime\norder by slow_run_started_at desc\nlimit 1\n)\nselect\nuri\n, method\n, count as \"合計\"\n, c_2xx as \"2xx\"\n, c_3xx as \"3xx\"\n, c_4xx as \"4xx\"\n, c_5xx as \"5xx\"\n, sum as \"合計時間\"\n, min as \"最短時間\"\n, max as \"最長時間\"\n, avg as \"平均時間\"\n, p90 as \"p90時間\"\nfrom nginx_access_runs\nwhere slow_run_started_at = (select slow_run_started_at from latest_slow_run)\norder by sum desc\n;"
    }
   ]
  },
  {
   "title": "新規パネル",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with latest_slow_run as (\nselect slow_run_started_at\nfrom nginx_access_runs\nwhere slow_run_started_at between $__fromTime and $__toTime\norder by slow_run_started_at desc\nlimit 1\n)\nselect\n'Nginx',\nformatDateTime(toTimeZone(slow_run_started_at, 'Asia/Tokyo'),'%H:%i:%S') as \"最新ベンチ開始\"\nfrom latest_slow_run\nwhere slow_run_started_at between $__fromTime and $__toTime\norder by slow_run_started_at desc\nlimit 1\n;"
    }
   ]
  },
  { "title": "Traces(パス・メソッド別のN+1問題)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "時間範囲内の最新ベンチの span数(for N+1問題)",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "with latest_slow_run as (\n  select log_started_at, log_ended_at\n  from slow_runs\n  where log_started_at between $__fromTime and $__toTime\n  order by log_started_at desc\n  limit 1\n), root_traces as (\n  -- TraceIdでグルーピング\n  -- 代表のSpanNameを抽出\n  select\n    TraceId as trace_id\n    , SpanAttributes['http.method'] as http_method\n    , SpanName as span_name\n  from otel_traces\n  where Timestamp between (select log_started_at from latest_slow_run) and (select log_ended_at from latest_slow_run)\n  and ParentSpanId = ''\n), traces as (\n  -- span_name: 代表スパン名\n  select\n    trace_id\n    , http_method\n    , min(span_name) as span_name\n    , count() as span_count\n    , sum(Duration) as sum_duration\n    , (select count() from otel_traces ot where ot.TraceId = trace_id and ot.SpanName like 'sql%') as sql_span_count\n  from otel_traces\n  join root_traces on trace_id = TraceId\n  group by trace_id, http_method\n)\n-- span_nameで更にグルーピング\n-- TraceIdは代表TraceId\n-- TraceIdという列名にすると、トレースへのリンクになる\n-- 平均span数が多いほど、N+1問題が起きている\nselect\n  span_name as \"span名\"\n  , http_method as \"method\"\n  , argMax(trace_id, sum_duration) as \"TraceId\"\n  , avg(span_count) as \"平均span数\"\n  , avg(sql_span_count) as \"平均sql_span数\"\n  , sum(span_count) as \"合計span数\"\n  , sum(sql_span_count) as \"合計sql_span数\"\n  , max(span_count) as \"最大span数\"\n  , max(sql_span_count) as \"最大sql_span数\"\n  , min(span_count) as \"最小span数\"\n  , min(sql_span_count) as \"最小sql_span数\"\nfrom traces\ngroup by span_name, http_method\norder by \"合計span数\" desc\n;\n"
    }
   ]
  },
  {
   "title": "新規パネル",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  'Traces'\n  , formatDateTime(toTimeZone(log_started_at, 'Asia/Tokyo'),'%H:%i:%S') as \"最新ベンチ開始\"\nfrom slow_runs\nwhere log_started_at between $__fromTime and $__toTime\norder by log_started_at desc\nlimit 1\n"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "with data as (\nselect\n  $__timeInterval(TimeUnix) as \"time\"\n  , splitByChar('.', ResourceAttributes['host.name'])[1] as private_ip\n  , Attributes['cpu'] as cpu\n  , Attributes['state'] as state\n  , sum(Value) as v\nfrom otel_metrics_sum\nwhere\n  ( $__fromTime <= time and time <= $__toTime )\n  and MetricName = 'system.cpu.time'\n  and private_ip = 'ip-192-168-1-10'\ngroup by private_ip, Attributes['cpu'], Attributes['state'], time\norder by time asc\n), diff as (\nselect\n  time, private_ip, cpu, state\n  , v - lag(v) over (partition by private_ip, cpu, state order by time) as diff\nfrom data\norder by time\n), total as (\nselect\n  time, private_ip, cpu\n  , sum(diff) as total\nfrom diff\ngroup by time, private_ip, cpu\n)\nselect\n  diff.time, private_ip, cpu\n  , sumIf(diff.diff, diff.state in ('user', 'system')) / total.total * 100 as \"CPU使用率\"\nfrom diff\njoin total using (time, cpu, private_ip)\nwhere diff.diff >= 0\ngroup by diff.time, private_ip, cpu, total.total\norder by diff.time\n"
    },
    {
     "rawSql": "with data as (\nselect\n  $__timeInterval(TimeUnix) as \"time\"\n  , splitByChar('.', ResourceAttributes['host.name'])[1] as private_ip\n  , Attributes['cpu'] as cpu\n  , Attributes['state'] as state\n  , sum(Value) as v\nfrom otel_metrics_sum\nwhere\n  ( $__fromTime <= time and time <= $__toTime )\n  and MetricName = 'system.cpu.time'\n  and private_ip = 'ip-192-168-1-30'\ngroup by private_ip, Attributes['cpu'], Attributes['state'], time\norder by time asc\n), diff as (\nselect\n  time, private_ip, cpu, state\n  , v - lag(v) over (partition by private_ip, cpu, state order by time) as diff\nfrom data\norder by time\n), total as (\nselect\n  time, private_ip, cpu\n  , sum(diff) as total\nfrom diff\ngroup by time, private_ip, cpu\n)\nselect\n  diff.time, private_ip, cpu\n  , sumIf(diff.diff, diff.state in ('user', 'system')) / total.total * 100 as \"CPU使用率\"\nfrom diff\njoin total using (time, cpu, private_ip)\nwhere diff.diff >= 0\ngroup by diff.time, private_ip, cpu, total.total\norder by diff.time\n"
    }
   ]
  }
 ]
}