{
 "title": "sample-dashboad",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "スコア", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "スコアの推移",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    toDateTime(started_at) AS started_at,\n    score AS \"スコア\"\nFROM results\nORDER BY started_at\n"
    }
   ]
  },
  {
   "title": "時間範囲内のベンチスコア",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select\nscore as \"スコア\"\n, dateDiff('second', started_at, ended_at) as \"時間(秒)\"\n, started_at as \"ベンチ開始\"\n, ended_at as \"ベンチ終了\"\nfrom results\nwhere started_at between $__fromTime and $__toTime\norder by started_at desc\nlimit 10\n;"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "with data as (\n  select\n    $__timeInterval(TimeUnix) as \"time\"\n    , splitByChar('.', ResourceAttributes['host.name'])[1] as private_ip\n    , Attributes['cpu'] as cpu\n    , Attributes['state'] as state\n    , sum(Value) as v\n  from otel_metrics_sum\n  where\n    ( $__fromTime <= time and time <= $__toTime )\n    and MetricName = 'system.cpu.time'\n    and private_ip = 'ip-192-168-1-10'\n  group by private_ip, Attributes['cpu'], Attributes['state'], time\n  order by time asc\n), diff as (\n  select\n    time\n    , private_ip\n    , cpu\n    , state\n    , v - lag(v) over (partition by private_ip, cpu, state order by time) as diff\n  from data\n  order by time\n), total as (\n  select\n    time\n    , private_ip\n    , cpu\n    , sum(diff) as total\n  from diff\n  group by time, private_ip, cpu\n)\nselect\n  diff.time\n  , private_ip\n  , cpu\n  , sumIf(diff.diff, diff.state in ('user', 'system')) / total.total * 100 as \"CPU使用率\"\nfrom diff\njoin total using (time, cpu, private_ip)\nwhere diff.diff >= 0\ngroup by diff.time, private_ip, cpu, total.total\norder by diff.time\n"
    }
   ]
  },
  { "title": "nx(パス・メソッド別のアクセスログ集計)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "時間範囲内の最新ベンチの Nginx のアクセスログ集計",
   "type": "table",
   "gridPos": { "h": 19, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "with latest_slow_run as (\nselect slow_run_started_at\nfrom nginx_access_runs\nwhere slow_run_started_at between $__fromTime and $__toTime\norder by slow_run_started_at desc\nlimit 1\n)\nselect\nuri\n, method\n, count as \"合計\"\n, c_2xx as \"2xx\"\n, c_3xx as \"3xx\"\n, c_4xx as \"4xx\"\n, c_5xx as \"5xx\"\n, sum as \"合計時間\"\n, min as \"最短時間\"\n, max as \"最長時間\"\n, avg as \"平均時間\"\n, p90 as \"p90時間\"\nfrom nginx_access_runs\nwhere slow_run_started_at = (select slow_run_started_at from latest_slow_run)\norder by sum desc\n;"
    }
   ]
  },
  {
   "title": "新規パネル",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with latest_slow_run as (\nselect slow_run_started_at\nfrom nginx_access_runs\nwhere slow_run_started_at between $__fromTime and $__toTime\norder by slow_run_started_at desc\nlimit 1\n)\nselect\n'Nginx',\nformatDateTime(toTimeZone(slow_run_started_at, 'Asia/Tokyo'),'%H:%i:%S') as \"最新ベンチ開始\"\nfrom latest_slow_run\nwhere slow_run_started_at between $__fromTime and $__toTime\norder by slow_run_started_at desc\nlimit 1\n;"
    }
   ]
  },
  { "title": "DBスロークエリ単位", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "新規パネル",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n'MySQL'\n,\nformatDateTime(toTimeZone(log_started_at, 'Asia/Tokyo'),'%H:%i:%S') as \"最新ベンチ開始\"\nfrom slow_runs\nwhere log_started_at between $__fromTime and $__toTime\norder by log_started_at desc\nlimit 1"
    }
   ]
  },
  {
   "title": "新規パネル",
   "type": "table",
   "gridPos": { "h": 12, "w": 19, "x": 4, "y": 36 },
   "targets": [
    {
     "rawSql": "with latest_slow_run as (\nselect log_started_at\nfrom slow_runs\nwhere log_started_at between $__fromTime and $__toTime\norder by log_started_at desc\nlimit 1\n)\nselect\nexample_query as \"クエリ\"\n, query_count as \"クエリ数\"\n, qtime_sum as \"合計時間\"\n, qtime_avg as \"平均時間\"\n, qtime_pct95 as \"p95時間\"\n, rows_exam_sum as \"合計走査行数\"\n, rows_exam_avg as \"平均走査行数\"\n, rows_exam_pct95 as \"p95走査行数\"\nfrom slow_queries\nwhere\nlog_started_at = (select log_started_at from latest_slow_run)\norder by qtime_sum desc\n;"
    }
   ]
  }
 ]
}